#!/bin/bash
rm -rf outputs spark-wc-out-*
mkdir outputs

spark-submit perWordDocumentCount.py seqFiles/billOfRights.txt.seq
mv spark-wc-out-perWordDocumentCount/part-00000 outputs/perWordDocumentCount

spark-submit createIndices.py seqFiles/complete-works-mark-twain.txt.seq
grep Mark spark-wc-out-createIndices/part-00000 > outputs/createIndices

spark-submit mostPopular.py seqFiles/billOfRights.txt.seq
mv spark-wc-out-mostPopular/part-00000 outputs/mostPopular